### ISSUE TITLE
.label 文件

### ISSUE THREAD

**Issue by chky1997** [ZYunfeii/KITTI-velodyne-viewer-matlab#2]
大佬您好，我想问下下载的kitti数据集它的标签格式是.label的形式，不是您博客里提到的那种，请问如何转换呢，感谢

**Comment by ZYunfeii** [comment]
你是在官网下的吗，官网下的3D点云标注就是txt




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZYunfeii/KITTI-velodyne-viewer-matlab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月13日(星期三) 上午9:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZYunfeii/KITTI-velodyne-viewer-matlab] .label 文件 (#2)





 
大佬您好，我想问下下载的kitti数据集它的标签格式是.label的形式，不是您博客里提到的那种，请问如何转换呢，感谢

**Comment by chky1997** [comment]
我明白了，我发现下的是semantickitti，感谢

**Comment by chky1997** [comment]
我明白了，我发现下的是semantickitti，感谢
